#' Ops.MFobject
#'
#' Check if an object is a correctly formed MFobject
#' 
#' @param a object
#'
#' @export
is.MFobject <- function(a){
  
 class(a) == "MFobject" && is.numeric(a) && !is.null(names(a)) && !any(duplicated(names(a)))
}


#' Ops.MFobject
#'
#' Operator behavior for MFobject S3 class
#' 
#' @param a numeric or MFobject
#' @param b numeric or MFobject
#'
#' @export
Ops.MFobject <- function(a,b){
  
  if (nargs() == 1L){
    switch(.Generic,
           `+` = ,
           `-` = NextMethod()
    )
    
  }else{
  
    
    
    
  if(class(a) == "MFobject"
    && class(b) == "MFobject"){
 switch(.Generic,
         `+` = NextMethod(),
         `-` = NextMethod(),
         `*` = ,
         `/` = ,
         `!=` = any(NextMethod()),
         `==` = all(NextMethod()),
         `<` = {a != b && all(a-b <= 0)},
         `>` = {a != b && all(a-b >= 0)},
         `<=` = {a == b || all(a-b <= 0)},
         `>=` = {a == b || all(a-b >= 0)}
         
  )
 
 
  }else if(class(a) != class(b)){
  
   NextMethod() 
    
  }}
}

#' print.MFobject
#'
#' Print method for MFobject S3 class
#' 
#' @param s MFobject
#'
#' @export
print.MFobject <- function(s){

   print(remakeMF(s))
   
}

#' getSenior3
#'
#'  calculate the sum of valences minus twice (the number of atoms minus 1) (to check for Senior's third theorem, "Golden Rule #2")[1][2][3]
#'
#'
#' @references 
#' \enumerate{
#' \item Kind T, Fiehn O (2007) Seven Golden Rules for heuristic filtering of molecular formulas obtained by accurate mass spectrometry. BMC Bioinformatics 8:105. doi: 10.1186/1471-2105-8-105
#' \item Senior JK (1951) Partitions and Their Representative Graphs. Am J Math 73:663. doi: 10.2307/2372318
#' \item Morikawa T, Newbold BT (2003) Analogous odd-even parities in mathematics and chemistry. Chemistry 12:445–450
#'}
#' @param MF MFobject as generated by \code{\link{makeMF}}
#'
getSenior3.MFobject <- function(MF){
  
  #if result is >= 0, formula is valid as per Senior's third theorem 
  sum(MF*getOption("MassTools.maxValences")) - 2*(sum(MF)-1)
  
}
